//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPI
    {
        public short RECORD_IDENTIFIER { get; set; }
        public string CHANGE_TYPE { get; set; }
        public int PRO_ORDER { get; set; }
        public long UPRN { get; set; }
        public string LPI_KEY { get; set; }
        public string LANGUAGE { get; set; }
        public short LOGICAL_STATUS { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<short> SAO_START_NUMBER { get; set; }
        public string SAO_START_SUFFIX { get; set; }
        public Nullable<short> SAO_END_NUMBER { get; set; }
        public string SAO_END_SUFFIX { get; set; }
        public string SAO_TEXT { get; set; }
        public Nullable<short> PAO_START_NUMBER { get; set; }
        public string PAO_START_SUFFIX { get; set; }
        public Nullable<short> PAO_END_NUMBER { get; set; }
        public string PAO_END_SUFFIX { get; set; }
        public string PAO_TEXT { get; set; }
        public int USRN { get; set; }
        public string USRN_MATCH_INDICATOR { get; set; }
        public string AREA_NAME { get; set; }
        public string LEVEL { get; set; }
        public string OFFICIAL_FLAG { get; set; }
    
        public virtual BLPU BLPU { get; set; }
        public virtual Street Street { get; set; }
    }
}
