//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;

    public partial class NLPG
    {
        public long Id { get; set; }
        public Nullable<long> uprn { get; set; }
        public string CLASSIFICATION_CODE { get; set; }
        public string sao_text { get; set; }
        public Nullable<short> sao_start_number { get; set; }
        public string sao_start_suffix { get; set; }
        public Nullable<short> sao_end_number { get; set; }
        public string sao_end_suffix { get; set; }
        public string pao_text { get; set; }
        public Nullable<short> pao_start_number { get; set; }
        public string pao_start_suffix { get; set; }
        public Nullable<short> pao_end_number { get; set; }
        public string pao_end_suffix { get; set; }
        public Nullable<int> usrn { get; set; }
        public Nullable<short> logical_status { get; set; }
        public string street_description { get; set; }
        public string town_name { get; set; }
        public string locality_name { get; set; }
        public string postcode_locator { get; set; }
        public Nullable<double> nlpg_x_coordinate { get; set; }
        public Nullable<double> nlpg_y_coordinate { get; set; }
        public string geo_single_address_label { get; set; }
    }
}
