//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;

    public partial class PAF
    {
        public long Id { get; set; }
        public short RECORD_IDENTIFIER { get; set; }
        public string CHANGE_TYPE { get; set; }
        public int PRO_ORDER { get; set; }
        public long UPRN { get; set; }
        public Nullable<long> PARENT_ADDRESSABLE_UPRN { get; set; }
        public int RM_UPRN { get; set; }
        public string ORGANISATION_NAME { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string SUB_BUILDING_NAME { get; set; }
        public string BUILDING_NAME { get; set; }
        public Nullable<short> BUILDING_NUMBER { get; set; }
        public string DEPENDENT_THOROUGHFARE { get; set; }
        public string THOROUGHFARE { get; set; }
        public string DOUBLE_DEPENDENT_LOCALITY { get; set; }
        public string DEPENDENT_LOCALITY { get; set; }
        public string POST_TOWN { get; set; }
        public string POSTCODE { get; set; }
        public string POSTCODE_TYPE { get; set; }
        public string WELSH_DEPENDENT_THOROUGHFARE { get; set; }
        public string WELSH_THOROUGHFARE { get; set; }
        public string WELSH_DOUBLE_DEPENDENT_LOCALITY { get; set; }
        public string WELSH_DEPENDENT_LOCALITY { get; set; }
        public string WELSH_POST_TOWN { get; set; }
        public string PO_BOX_NUMBER { get; set; }
        public System.DateTime PROCESS_DATE { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public double X_COORDINATE { get; set; }
        public double Y_COORDINATE { get; set; }
        public string FULLADDRESS { get; set; }
        public int USRN { get; set; }
    }
}
