//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using Microsoft.EntityFrameworkCore;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class QuestOSEntities : DbContext
    {
        public QuestOSEntities()
            : base("name=QuestOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Road> Roads { get; set; }
        public virtual DbSet<RoadLink> RoadLinks { get; set; }
        public virtual DbSet<RoadNetworkMember> RoadNetworkMembers { get; set; }
        public virtual DbSet<RoadNode> RoadNodes { get; set; }
        public virtual DbSet<RoadRouteInfo> RoadRouteInfoes { get; set; }
        public virtual DbSet<RoadType> RoadTypes { get; set; }
        public virtual DbSet<RoadName> RoadNames { get; set; }
        public virtual DbSet<StaticRoadLink> StaticRoadLinks { get; set; }
        public virtual DbSet<StaticRoadNode> StaticRoadNodes { get; set; }
        public virtual DbSet<StaticRoadLinksGeom> StaticRoadLinksGeoms { get; set; }
        public virtual DbSet<RoadJunctionsView> RoadJunctionsViews { get; set; }
        public virtual DbSet<PAF> PAFs { get; set; }
        public virtual DbSet<RoadLinkView> RoadLinkViews { get; set; }
        public virtual DbSet<RoadNameView> RoadNameViews { get; set; }
        public virtual DbSet<StaticRoadLinkView> StaticRoadLinkViews { get; set; }
        public virtual DbSet<StaticRoadNodeView> StaticRoadNodeViews { get; set; }
        public virtual DbSet<Junction> Junctions { get; set; }
    
        public virtual int PostprocessITNLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PostprocessITNLoad");
        }
    }
}
