//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadNetworkMember
    {
        public int RoadNetworkMemberId { get; set; }
        public string RoadFid { get; set; }
        public string NetworkFid { get; set; }
        public Nullable<int> RoadId { get; set; }
        public Nullable<int> RoadLinkId { get; set; }
    
        public virtual Road Road { get; set; }
    }
}
