//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;

    public partial class RoadName
    {
        public string RoadName1 { get; set; }
        public Nullable<int> ToRoadNodeId { get; set; }
        public Nullable<int> FromRoadNodeId { get; set; }
        public int RoadLinkId { get; set; }
        public int RoadId { get; set; }
    }
}
