//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadLinkView
    {
        public int RoadLinkId { get; set; }
        public Nullable<int> FromRoadNodeId { get; set; }
        public Nullable<bool> Include { get; set; }
        public string fid { get; set; }
        public string RoadType { get; set; }
        public Nullable<int> ToRoadNodeId { get; set; }
        public int RoadTypeId { get; set; }
        public string natureOfRoad { get; set; }
        public string WKT { get; set; }
        public Nullable<int> FromGrade { get; set; }
        public Nullable<int> ToGrade { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public string Expr1 { get; set; }
    }
}
