//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoadLink()
        {
            this.RoadRouteInfoes = new HashSet<RoadRouteInfo>();
            this.RoadRouteInfoes1 = new HashSet<RoadRouteInfo>();
        }
    
        public int RoadLinkId { get; set; }
        public string fid { get; set; }
        public string RoadType { get; set; }
        public string WKT { get; set; }
        public Nullable<int> FromRoadNodeId { get; set; }
        public Nullable<int> ToRoadNodeId { get; set; }
        public string FromFid { get; set; }
        public string ToFid { get; set; }
        public string natureOfRoad { get; set; }
        public Nullable<bool> Include { get; set; }
        public Nullable<int> FromGrade { get; set; }
        public Nullable<int> ToGrade { get; set; }
    
        public virtual RoadLink RoadLink1 { get; set; }
        public virtual RoadLink RoadLink2 { get; set; }
        public virtual RoadNode RoadNode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadRouteInfo> RoadRouteInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadRouteInfo> RoadRouteInfoes1 { get; set; }
    }
}
