//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadJunctionsView
    {
        public string R1 { get; set; }
        public string R2 { get; set; }
        public int RoadId1 { get; set; }
        public int RoadId2 { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
    }
}
