//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoadNode()
        {
            this.RoadLinks = new HashSet<RoadLink>();
            this.StaticRoadLinks = new HashSet<StaticRoadLink>();
            this.StaticRoadLinks1 = new HashSet<StaticRoadLink>();
        }
    
        public int RoadNodeId { get; set; }
        public string fid { get; set; }
        public Nullable<bool> Include { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadLink> RoadLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaticRoadLink> StaticRoadLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaticRoadLink> StaticRoadLinks1 { get; set; }
    }
}
