//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;

    public partial class StaticRoadLinksGeom
    {
        public int RoadLinkId { get; set; }
        public Nullable<int> FromRoadNodeId { get; set; }
        public Nullable<int> ToRoadNodeId { get; set; }
        public string RoadName { get; set; }
        public int RoadTypeId { get; set; }
        public string WKT { get; set; }
        public Nullable<bool> FromOneWay { get; set; }
        public Nullable<bool> FromNoTurn { get; set; }
        public Nullable<bool> FromNoEntry { get; set; }
        public Nullable<bool> FromMandatoryTurn { get; set; }
        public Nullable<bool> ToOneWay { get; set; }
        public Nullable<bool> ToNoTurn { get; set; }
        public Nullable<bool> ToNoEntry { get; set; }
        public Nullable<bool> ToMandatoryTurn { get; set; }
        public int FromGrade { get; set; }
        public int ToGrade { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public string natureOfRoad { get; set; }
    }
}
