//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StreetDescriptor
    {
        public short RECORD_IDENTIFIER { get; set; }
        public string CHANGE_TYPE { get; set; }
        public int PRO_ORDER { get; set; }
        public int USRN { get; set; }
        public string STREET_DESCRIPTION { get; set; }
        public string LOCALITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public string ADMINSTRATIVE_AREA { get; set; }
        public string LANGUAGE { get; set; }
    
        public virtual Street Street { get; set; }
    }
}
