//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.OS.Model
{
    using System;

    public partial class Successor
    {
        public Nullable<short> RECORD_IDENTIFIER { get; set; }
        public string CHANGE_TYPE { get; set; }
        public Nullable<int> PRO_ORDER { get; set; }
        public Nullable<long> UPRN { get; set; }
        public string SUCC_KEY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<long> SUCCESSOR1 { get; set; }
    
        public virtual BLPU BLPU { get; set; }
    }
}
