//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Callsign
    {
        public Callsign()
        {
            this.Resources = new HashSet<Resource>();
        }
    
        public int CallsignID { get; set; }
        public string Callsign1 { get; set; }
    
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
