//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoverageMapDefinition
    {
        public int CoverageMapDefinitionId { get; set; }
        public string Name { get; set; }
        public string VehicleCodes { get; set; }
        public Nullable<int> MinuteLimit { get; set; }
        public string StyleCode { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string RoutingResource { get; set; }
    }
}
