//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceView
    {
        public string Status { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<bool> Busy { get; set; }
        public Nullable<bool> BusyEnroute { get; set; }
        public Nullable<bool> NoSignal { get; set; }
        public Nullable<bool> Offroad { get; set; }
        public Nullable<bool> Rest { get; set; }
        public int ResourceID { get; set; }
        public string Callsign { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> Direction { get; set; }
        public string Skill { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> FleetNo { get; set; }
        public string Sector { get; set; }
        public string Serial { get; set; }
        public string Emergency { get; set; }
        public string Destination { get; set; }
        public string Agency { get; set; }
        public string Class { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string Comment { get; set; }
        public string Road { get; set; }
        public Nullable<long> Revision { get; set; }
        public Nullable<int> ResourceStatusPrevID { get; set; }
        public string PrevStatus { get; set; }
        public string ResourceTypeGroup { get; set; }
        public string ResourceType { get; set; }
        public Nullable<float> DestLatitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<int> ResourceTypeId { get; set; }
        public Nullable<float> Latitude { get; set; }
        public Nullable<float> DestLongitude { get; set; }
    }
}
