//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadSpeedMatrixHoWSummary
    {
        public long Id { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public Nullable<int> MaxRoadType { get; set; }
        public Nullable<int> MaxVehicleType { get; set; }
        public Nullable<int> HourCount { get; set; }
        public Nullable<int> MinX { get; set; }
        public Nullable<int> MaxX { get; set; }
        public Nullable<int> MinY { get; set; }
        public Nullable<int> MaxY { get; set; }
        public Nullable<int> XCount { get; set; }
        public Nullable<int> YCount { get; set; }
    }
}
