//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{

    public partial class tRelationCreation
    {
        public long RelationId { get; set; }
        public long @ref { get; set; }
        public int type { get; set; }
        public int role { get; set; }
        public int sort { get; set; }
    }
}
