//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{

    public partial class tWay
    {
        public long Id { get; set; }
        public System.Data.Entity.Spatial.DbGeography line { get; set; }
    }
}
