//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Research.Model
{
    using System;

    public partial class Activation
    {
        public int ActivationId { get; set; }
        public long IncidentId { get; set; }
        public Nullable<System.DateTime> Dispatched { get; set; }
        public Nullable<System.DateTime> Arrived { get; set; }
        public string Callsign { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
    }
}
