//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Research.Model
{

    public partial class AvlsRoad
    {
        public int AvlsRoadId { get; set; }
        public int AvlsId { get; set; }
        public int RoadLinkEdgeId { get; set; }
        public int RoadTypeId { get; set; }
        public float DistanceToRoad { get; set; }
    }
}
