//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Research.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentRouteRun
    {
        public int IncidentRouteRunId { get; set; }
        public string Parameters { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
