//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Research.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidentRoute()
        {
            this.IncidentRouteEstimates = new HashSet<IncidentRouteEstimate>();
            this.RoadSpeedItems = new HashSet<RoadSpeedItem>();
        }
    
        public int IncidentRouteID { get; set; }
        public string Callsign { get; set; }
        public Nullable<long> IncidentId { get; set; }
        public bool Scanned { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ActualDuration { get; set; }
        public Nullable<bool> IsBadGPS { get; set; }
        public System.Data.Entity.Spatial.DbGeometry ActualRoute { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentRouteEstimate> IncidentRouteEstimates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadSpeedItem> RoadSpeedItems { get; set; }
    }
}
