//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Research.Model
{
    using System;

    public partial class RoadSpeedItem
    {
        public int IncidentRouteRunId { get; set; }
        public int IncidentRouteId { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Speed { get; set; }
        public Nullable<int> RoadLinkEdgeId { get; set; }
    
        public virtual IncidentRoute IncidentRoute { get; set; }
    }
}
