//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quest.Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;STORMTelServer&gt;
        ///  &lt;CallAnswered&gt;
        ///    &lt;WorkstationId&gt;{Extension}&lt;/WorkstationId&gt;
        ///    &lt;CallingLineIdentity&gt;{CLI}&lt;/CallingLineIdentity&gt;
        ///    &lt;MessageId&gt;{CallID}&lt;/MessageId&gt;
        ///  &lt;/CallAnswered&gt;
        ///&lt;/STORMTelServer&gt;.
        /// </summary>
        internal static string StormConnected {
            get {
                return ResourceManager.GetString("StormConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;STORMTelServer&gt;
        ///  &lt;CallerDetails&gt;
        ///    &lt;MessageId&gt;{CallID}&lt;/MessageId&gt;
        ///    &lt;EISECData&gt;
        ///      &lt;TelephoneNumber&gt;{CLI}&lt;/TelephoneNumber&gt;
        ///      &lt;Name&gt;{Name}&lt;/Name&gt;
        ///      &lt;LocLine1&gt;{Address1}&lt;/LocLine1&gt;
        ///      &lt;LocLine2&gt;{Address2}&lt;/LocLine2&gt;
        ///      &lt;LocLine3&gt;{Address3}&lt;/LocLine3&gt;
        ///      &lt;LocLine4&gt;{Address4}&lt;/LocLine4&gt;
        ///      &lt;LocLine5&gt;{Address5}&lt;/LocLine5&gt;
        ///      &lt;LocLine6&gt;{Address6}&lt;/LocLine6&gt;
        ///    &lt;/EISECData&gt;
        ///  &lt;/CallerDetails&gt;
        ///&lt;/STORMTelServer&gt;.
        /// </summary>
        internal static string StormDetails {
            get {
                return ResourceManager.GetString("StormDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;STORMTelServer&gt;
        ///  &lt;HeartBeatResponse/&gt;
        ///&lt;/STORMTelServer&gt;.
        /// </summary>
        internal static string StormHeartbeat {
            get {
                return ResourceManager.GetString("StormHeartbeat", resourceCulture);
            }
        }
    }
}
