//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.UnitTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>app,approach </string>\r\n  <string>ave,avenue</string>\r\n  <string>bri,bridg" +
            "e</string>\r\n  <string>bdwy,broadway </string>\r\n  <string>br,british rail</string" +
            ">\r\n  <string>cem,cemetery</string>\r\n  <string>clo,close</string>\r\n  <string>cnr," +
            "corner</string>\r\n  <string>ct,court</string>\r\n  <string>cres,crescent</string>\r\n" +
            "  <string>x,cross </string>\r\n  <string>dri,drive </string>\r\n  <string>e,east </s" +
            "tring>\r\n  <string>est,estate </string>\r\n  <string>fc,football club</string>\r\n  <" +
            "string>gdns,gardens</string>\r\n  <string>la,lane </string>\r\n  <string>lt,lte</str" +
            "ing>\r\n  <string>mans,mansions </string>\r\n  <string>mkt,market </string>\r\n  <stri" +
            "ng>mt,mount </string>\r\n  <string>n,north </string>\r\n  <string>pde,parade </strin" +
            "g>\r\n  <string>pk,park </string>\r\n  <string>pl,place </string>\r\n  <string>pol,pol" +
            "ice </string>\r\n  <string>rec,recreation </string>\r\n  <string>rd,road</string>\r\n " +
            " <string>rbt,roundabout </string>\r\n  <string>st,saint </string>\r\n  <string>sch,s" +
            "chool </string>\r\n  <string>s,south </string>\r\n  <string>sq,square </string>\r\n  <" +
            "string>stn,station </string>\r\n  <string>st,street </string>\r\n  <string>gt,great " +
            "</string>\r\n  <string>grn,green </string>\r\n  <string>gro,grove </string>\r\n  <stri" +
            "ng>hosp,hospital </string>\r\n  <string>hse,house </string>\r\n  <string>ter,terrace" +
            " </string>\r\n  <string>tra,trading </string>\r\n  <string>lt,u/g</string>\r\n  <strin" +
            "g>lt,underground</string>\r\n  <string>w,west</string>\r\n  <string>&amp;,and</strin" +
            "g>\r\n  <string>1st,first</string>\r\n  <string>2nd,second</string>\r\n  <string>3rd,t" +
            "hird</string>\r\n  <string>4th,fourth</string>\r\n  <string>5th,fifth</string>\r\n  <s" +
            "tring>6th,sixth</string>\r\n  <string>7th,seventh</string>\r\n  <string>8th,eighth</" +
            "string>\r\n  <string>9th,ninth</string>\r\n  <string>ac,central london training cent" +
            "re</string>\r\n  <string>ad,belgravia</string>\r\n  <string>ag,grosvenor</string>\r\n " +
            " <string>ap,pimlico</string>\r\n  <string>av,victoria</string>\r\n  <string>ax,chari" +
            "ng x</string>\r\n  <string>az,aldwych</string>\r\n  <string>ba,portobello</string>\r\n" +
            "  <string>bc,chelsea</string>\r\n  <string>bd,kensington</string>\r\n  <string>be,ce" +
            "ntral kensington</string>\r\n  <string>bh,notting hill</string>\r\n  <string>bk,holl" +
            "and</string>\r\n  <string>bn,notting dale</string>\r\n  <string>bs,kensington and ch" +
            "elsea</string>\r\n  <string>pg,penge</string>\r\n  <string>pkx,brockley</string>\r\n  " +
            "<string>plx,lewisham</string>\r\n  <string>pm,st mary cray</string>\r\n  <string>pn," +
            "orpington</string>\r\n  <string>pp,deptford</string>\r\n  <string>pr,bromley</string" +
            ">\r\n  <string>ps,sydenham</string>\r\n  <string>pw,w wickham</string>\r\n  <string>px" +
            ",egerton lodge</string>\r\n  <string>py,bromley and orpington</string>\r\n  <string>" +
            "pz,lewisham</string>\r\n  <string>q99,wembley stadium</string>\r\n  <string>qa,harro" +
            "w</string>\r\n  <string>qc,chalkhill</string>\r\n  <string>qd,wembley</string>\r\n  <s" +
            "tring>qe,edgware</string>\r\n  <string>qh,harlesden</string>\r\n  <string>qk,kilburn" +
            "</string>\r\n  <string>ql,willesden grn</string>\r\n  <string>qp,pinner</string>\r\n  " +
            "<string>qr,carey way</string>\r\n  <string>qs,weststreet</string>\r\n  <string>qw,we" +
            "aldstone</string>\r\n  <string>qy,kingsbury</string>\r\n  <string>by,chelsea sector<" +
            "/string>\r\n  <string>ca,portman</string>\r\n  <string>cd,w end central</string>\r\n  " +
            "<string>cg,covent garden</string>\r\n  <string>cl,leicester sq</string>\r\n  <string" +
            ">cm,mayfair</string>\r\n  <string>cp,city of london pol</string>\r\n  <string>cp4,ci" +
            "ty of london pol</string>\r\n  <string>cp5,city of london pol</string>\r\n  <string>" +
            "cp6,city of london pol</string>\r\n  <string>cs,soho</string>\r\n  <string>ctx,tybur" +
            "n</string>\r\n  <string>cw,westminster</string>\r\n  <string>db,bayswater</string>\r\n" +
            "  <string>dd,paddington grn</string>\r\n  <string>dm,marylebone</string>\r\n  <strin" +
            "g>dq,queens pk</string>\r\n  <string>dr,harrow rd</string>\r\n  <string>ds,st johns " +
            "wood</string>\r\n  <string>dv,maida vale</string>\r\n  <string>dw,westbourne</string" +
            ">\r\n  <string>dz,dorset sq</string>\r\n  <string>ed,albany st</string>\r\n  <string>e" +
            "h,hampstead</string>\r\n  <string>ek,kentish town</string>\r\n  <string>eo,holborn</" +
            "string>\r\n  <string>esb,empress state bldg</string>\r\n  <string>ew,w hampstead</st" +
            "ring>\r\n  <string>ez,kentish town</string>\r\n  <string>ff,fulham</string>\r\n  <stri" +
            "ng>fh,hammersmith</string>\r\n  <string>fs,shepherds bush</string>\r\n  <string>fz,h" +
            "ammersmith</string>\r\n  <string>ga,dalston</string>\r\n  <string>gd,shoreditch</str" +
            "ing>\r\n  <string>gh,hackney</string>\r\n  <string>gl,central newington</string>\r\n  " +
            "<string>gn,stoke newington</string>\r\n  <string>gs,stamford hill</string>\r\n  <str" +
            "ing>qz,kilburn</string>\r\n  <string>ra,plumstead</string>\r\n  <string>rb,belvedere" +
            "</string>\r\n  <string>rdx,hyde pk</string>\r\n  <string>re,bexley</string>\r\n  <stri" +
            "ng>rf,greenwich - neighbourhood</string>\r\n  <string>rg,greenwich</string>\r\n  <st" +
            "ring>rh,warspite rd</string>\r\n  <string>ri,richmond pk</string>\r\n  <string>rj,ke" +
            "nt</string>\r\n  <string>rk,westcombe pk</string>\r\n  <string>rl,marlowe hse</strin" +
            "g>\r\n  <string>rm,eltham</string>\r\n  <string>rn,greenwich pk</string>\r\n  <string>" +
            "ro,royal parks ocu</string>\r\n  <string>rq,st jamess pk</string>\r\n  <string>rr,br" +
            "ompton cem</string>\r\n  <string>rs,sidcup</string>\r\n  <string>rt,thamesmead</stri" +
            "ng>\r\n  <string>ru,bushy pk</string>\r\n  <string>rv,charlton car pound</string>\r\n " +
            " <string>rw,woolwich</string>\r\n  <string>ry,bexleyheath</string>\r\n  <string>rz,r" +
            "egents pk</string>\r\n  <string>sa,barnet</string>\r\n  <string>sc,colindale</string" +
            ">\r\n  <string>sf,finchley</string>\r\n  <string>sg,golders grn</string>\r\n  <string>" +
            "si,kingsgate</string>\r\n  <string>sj,hertfordshire</string>\r\n  <string>sk,whetsto" +
            "ne - neighbourhood</string>\r\n  <string>sx,barnet borough</string>\r\n  <string>t1," +
            "transport ocu</string>\r\n  <string>t2,tfl northwest area</string>\r\n  <string>t3,t" +
            "fl northeast area</string>\r\n  <string>t4,tfl southeast area</string>\r\n  <string>" +
            "t5,tfl southwest area</string>\r\n  <string>tb,brentford</string>\r\n  <string>tc,ch" +
            "iswick</string>\r\n  <string>gv,hackney sector</string>\r\n  <string>gx,hoxton</stri" +
            "ng>\r\n  <string>ha,arbour sq</string>\r\n  <string>hd,leman st</string>\r\n  <string>" +
            "hh,limehouse</string>\r\n  <string>hi,isle of dogs</string>\r\n  <string>hr,brick la" +
            "</string>\r\n  <string>ht,tower hamlets</string>\r\n  <string>hw,bow</string>\r\n  <st" +
            "ring>ic,london city airport</string>\r\n  <string>id,heathrow</string>\r\n  <string>" +
            "ii,inner</string>\r\n  <string>io,outer</string>\r\n  <string>jb,barkingside</string" +
            ">\r\n  <string>jc,chingford</string>\r\n  <string>je,lea bridge</string>\r\n  <string>" +
            "jf,woodford</string>\r\n  <string>jh,chadwell heath</string>\r\n  <string>ji,ilford<" +
            "/string>\r\n  <string>jj,essex</string>\r\n  <string>jk,walthamstow town</string>\r\n " +
            " <string>jl,leyton</string>\r\n  <string>jm,waltham hse</string>\r\n  <string>jn,wan" +
            "stead</string>\r\n  <string>jp,waltham forest</string>\r\n  <string>jq,ilford</strin" +
            "g>\r\n  <string>jr,rigg app</string>\r\n  <string>js,leytonstone</string>\r\n  <string" +
            ">ju,uplands patrol base</string>\r\n  <string>jv,valentine</string>\r\n  <string>jw," +
            "walthamstow</string>\r\n  <string>jy,claygate hse pol stn</string>\r\n  <string>jz,c" +
            "hingford</string>\r\n  <string>ka,harold hill</string>\r\n  <string>kb,barking</stri" +
            "ng>\r\n  <string>kc,hornchurch</string>\r\n  <string>kd,romford</string>\r\n  <string>" +
            "td,hounslow</string>\r\n  <string>te,hounslow - n neighbourhood</string>\r\n  <strin" +
            "g>tf,feltham</string>\r\n  <string>th,ham</string>\r\n  <string>tk,bedfont</string>\r" +
            "\n  <string>tl,transport for london</string>\r\n  <string>tn,barnes</string>\r\n  <st" +
            "ring>tr,richmond</string>\r\n  <string>tt,teddington</string>\r\n  <string>tw,twicke" +
            "nham</string>\r\n  <string>tx,hounslow borough</string>\r\n  <string>ty,sovereign ga" +
            "te</string>\r\n  <string>tz,twickenham</string>\r\n  <string>vii,seventh</string>\r\n " +
            " <string>vk,kingston</string>\r\n  <string>vm,mitcham</string>\r\n  <string>vn,new m" +
            "alden</string>\r\n  <string>vq,wimbledon</string>\r\n  <string>vr,morden - neighbour" +
            "hood</string>\r\n  <string>vs,surbiton</string>\r\n  <string>vt,kingston</string>\r\n " +
            " <string>vw,wimbledon</string>\r\n  <string>wa,battersea</string>\r\n  <string>wd,to" +
            "oting</string>\r\n  <string>wf,earlsfield</string>\r\n  <string>wg,nightingale la</s" +
            "tring>\r\n  <string>wh,wandsworth sector</string>\r\n  <string>wj,jubilee hse</strin" +
            "g>\r\n  <string>wl,lavender hill</string>\r\n  <string>wn,nine elms</string>\r\n  <str" +
            "ing>wp,putney</string>\r\n  <string>wr,roehampton</string>\r\n  <string>wt,trinity r" +
            "d</string>\r\n  <string>ww,wandsworth</string>\r\n  <string>xa,acton</string>\r\n  <st" +
            "ring>xb,ealing borough</string>\r\n  <string>xc,w drayton custody at polar pk</str" +
            "ing>\r\n  <string>ke,e ham</string>\r\n  <string>kf,forest gate</string>\r\n  <string>" +
            "kg,dagenham</string>\r\n  <string>kh,havering</string>\r\n  <string>kk,marks gate</s" +
            "tring>\r\n  <string>kl,collier row</string>\r\n  <string>km,rainham</string>\r\n  <str" +
            "ing>kn,n woolwich</string>\r\n  <string>ko,plaistow</string>\r\n  <string>kq,forest " +
            "gate</string>\r\n  <string>kr,dagenham - neighbourhood</string>\r\n  <string>ks,stra" +
            "tford</string>\r\n  <string>kt,canning town</string>\r\n  <string>ku,upminster</stri" +
            "ng>\r\n  <string>kv,cam rd</string>\r\n  <string>kw,freshwharf patrol base</string>\r" +
            "\n  <string>kx,blackburn hse</string>\r\n  <string>ky,hertford hse</string>\r\n  <str" +
            "ing>kz,eagle hse</string>\r\n  <string>lc,cavendish rd</string>\r\n  <string>ld,brix" +
            "ton</string>\r\n  <string>lg,gipsy hill</string>\r\n  <string>lk,kennington</string>" +
            "\r\n  <string>ll,larkhall la</string>\r\n  <string>lm,clapham</string>\r\n  <string>ls" +
            ",streatham</string>\r\n  <string>lx,lambeth borough</string>\r\n  <string>mb,borough" +
            " and walworth</string>\r\n  <string>mc,camberwell</string>\r\n  <string>md,southwark" +
            "</string>\r\n  <string>me,e dulwich</string>\r\n  <string>mh,nunhead</string>\r\n  <st" +
            "ring>mm,peckham</string>\r\n  <string>mr,rotherhithe</string>\r\n  <string>ms,walwor" +
            "th</string>\r\n  <string>na,archway</string>\r\n  <string>nd,kings x rd</string>\r\n  " +
            "<string>xd,ealing</string>\r\n  <string>xe,w drayton</string>\r\n  <string>xf,harefi" +
            "eld</string>\r\n  <string>xg,greenford</string>\r\n  <string>xh,hillingdon</string>\r" +
            "\n  <string>xi,hanwell</string>\r\n  <string>xj,thames valley</string>\r\n  <string>x" +
            "n,northwood</string>\r\n  <string>xp,perivale</string>\r\n  <string>xr,ruislip</stri" +
            "ng>\r\n  <string>xs,southall</string>\r\n  <string>xu,uxbridge</string>\r\n  <string>x" +
            "v,perivale car pound</string>\r\n  <string>xy,hayes</string>\r\n  <string>ya,st anns" +
            " rd</string>\r\n  <string>yb,gt cambridge ind est</string>\r\n  <string>yd,wood grn<" +
            "/string>\r\n  <string>ydl,lymington ave</string>\r\n  <string>ydq,quicksilver</strin" +
            "g>\r\n  <string>ye,edmonton</string>\r\n  <string>yf,enfield</string>\r\n  <string>yh," +
            "highgate</string>\r\n  <string>yi,fishmongers arms</string>\r\n  <string>yl,lordship" +
            "</string>\r\n  <string>ym,muswell hill</string>\r\n  <string>yp,ponders end</string>" +
            "\r\n  <string>yq,hornsey</string>\r\n  <string>yr,hornsey</string>\r\n  <string>ys,sou" +
            "thgate</string>\r\n  <string>yt,tottenham</string>\r\n  <string>yw,winchmore hill</s" +
            "tring>\r\n  <string>yz,edmonton</string>\r\n  <string>za,addington</string>\r\n  <stri" +
            "ng>zb,banstead</string>\r\n  <string>zc,carshalton</string>\r\n  <string>zd,croydon<" +
            "/string>\r\n  <string>nh,holloway</string>\r\n  <string>ni,islington</string>\r\n  <st" +
            "ring>nn,islington - n neighbourhood</string>\r\n  <string>ns,islington - s neighbo" +
            "urhood</string>\r\n  <string>nv,highbury vale</string>\r\n  <string>ny,caledonian</s" +
            "tring>\r\n  <string>pa,catford</string>\r\n  <string>pb,beckenham</string>\r\n  <strin" +
            "g>pc,chislehurst</string>\r\n  <string>pd,bellingham and downham</string>\r\n  <stri" +
            "ng>pe,bromley - se neighbourhood</string>\r\n  <string>zdq,croydon custody centre<" +
            "/string>\r\n  <string>zi,ambassador hse</string>\r\n  <string>zj,surrey</string>\r\n  " +
            "<string>zk,kenley</string>\r\n  <string>zn,s norwood</string>\r\n  <string>zp,epsom<" +
            "/string>\r\n  <string>zr,worcester pk</string>\r\n  <string>zs,croydon sector</strin" +
            "g>\r\n  <string>zt,sutton</string>\r\n  <string>zw,wallington</string>\r\n  <string>zx" +
            ",croydon town centre</string>\r\n  <string>zy,norbury</string>\r\n  <string>zz,sutto" +
            "n</string>\r\n  <string>afc,arsenal football club</string>\r\n  <string>arc,adolesce" +
            "nt resource centre</string>\r\n  <string>b99,earls ct exhibition centre</string>\r\n" +
            "  <string>bma (hse),british medical association (hse)</string>\r\n  <string>bpr,bu" +
            "ckingham palace rd </string>\r\n  <string>btna,blackwell tunnel north approach</st" +
            "ring>\r\n  <string>btsa,blackwell tunnel south approach</string>\r\n  <string>bwfe,b" +
            "roadwater farm est</string>\r\n  <string>bxsc,brent cross shopping centre</string>" +
            "\r\n  <string>ccc,central criminal ct</string>\r\n  <string>ceu,cargo exit unit</str" +
            "ing>\r\n  <string>colmc,city of london magistrates courts</string>\r\n  <string>cp99" +
            ",bank of england</string>\r\n  <string>cwa,chessington world of adventure</string>" +
            "\r\n  <string>ebc,ealing broadway centre</string>\r\n  <string>ebs,early baggage sea" +
            "rch</string>\r\n  <string>eidr,e india dock rd </string>\r\n  <string>ep1-ep8,entry " +
            "point 1 - entry point 8</string>\r\n  <string>epr,eastern perimeter rd</string>\r\n " +
            " <string>ex1-ep13,exit point 1 - exit point 13</string>\r\n  <string>fcc,flight co" +
            "nnections centre</string>\r\n  <string>fco,foreign and commonwealth office</string" +
            ">\r\n  <string>gpe,grahame pk est</string>\r\n  <string>h99,tower of london</string>" +
            "\r\n  <string>hac,honourable artillery company</string>\r\n  <string>hcmc,highbury c" +
            "nr magistrates court</string>\r\n  <string>hlgs,hanger lane gyratory system</strin" +
            "g>\r\n  <string>hpc,hyde pk cnr</string>\r\n  <string>ica,institute of contemporary " +
            "art</string>\r\n  <string>ire,inner ring e</string>\r\n  <string>irw,inner ring w</s" +
            "tring>\r\n  <string>itn,independent television news</string>\r\n  <string>kgs,kensin" +
            "gton gdns sq</string>\r\n  <string>lap,london airport</string>\r\n  <string>latcc,lo" +
            "ndon air traffic control centre</string>\r\n  <string>lca,london city airport</str" +
            "ing>\r\n  <string>lgw,london gatwick airport</string>\r\n  <string>lhr,london heathr" +
            "ow airport</string>\r\n  <string>lift,london international freight terminal</strin" +
            "g>\r\n  <string>lll,leyton leisure lagoon</string>\r\n  <string>lph,london park hote" +
            "l</string>\r\n  <string>lts,lower thames st</string>\r\n  <string>lvic,lea valley ic" +
            "e centre</string>\r\n  <string>maff,ministry of agriculture fisheries &amp; food</" +
            "string>\r\n  <string>mod,ministry of defence</string>\r\n  <string>ncgm,new covent g" +
            "arden market</string>\r\n  <string>nhg,notting hill gate</string>\r\n  <string>nkr,n" +
            "ew kent rd</string>\r\n  <string>npl,national physical laboratory</string>\r\n  <str" +
            "ing>npr,northern perimeter rd</string>\r\n  <string>npy,new palace yard</string>\r\n" +
            "  <string>okr,old kent rd</string>\r\n  <string>opy,old palace yard</string>\r\n  <s" +
            "tring>pdsa,peoples dispensary for sick animals </string>\r\n  <string>qb,queens bl" +
            "dg</string>\r\n  <string>rcj,royal courts of justice</string>\r\n  <string>rfu,rugby" +
            " football union</string>\r\n  <string>rhh,royal home &amp; hospital</string>\r\n  <s" +
            "tring>rph,regent palace hotel</string>\r\n  <string>rspca,royal society for the pr" +
            "evention of cruelty to animals</string>\r\n  <string>rvpb,royal victoria patriotic" +
            " building </string>\r\n  <string>sah,south africa house</string>\r\n  <string>sklp,s" +
            "hree kuch leva patel</string>\r\n  <string>snt,safer neighbourhood team</string>\r\n" +
            "  <string>spr,southern perimeter rd</string>\r\n  <string>swmc,s western magistrat" +
            "es court</string>\r\n  <string>ta centre,territorial army centre</string>\r\n  <stri" +
            "ng>tba - tbk,technical block a - technical block k</string>\r\n  <string>thfc,tott" +
            "enham hotspur football club</string>\r\n  <string>thl,thatched house lodge</string" +
            ">\r\n  <string>tuc,trades union congress</string>\r\n  <string>tvu,thames valley uni" +
            "versity</string>\r\n  <string>unl,university of north london</string>\r\n  <string>u" +
            "ow,university of westminster</string>\r\n  <string>uts,upper thames st</string>\r\n " +
            " <string>vbr,vauxhall bri rd </string>\r\n  <string>wee,worlds end est</string>\r\n " +
            " <string>widr,w india dock rd </string>\r\n  <string>wpr,western perimeter rd </st" +
            "ring>\r\n  <string>ydcc,wood green crown court</string>\r\n  <string>ymca,young mens" +
            " christian association</string>\r\n  <string>ywca,young womens christian associati" +
            "on</string>\r\n  <string>b99,sw5</string>\r\n  <string>b99 2,sw5</string>\r\n  <string" +
            ">cp99,ec2</string>\r\n  <string>cx99,wc2</string>\r\n  <string>f99,w12</string>\r\n  <" +
            "string>h99,ec3</string>\r\n  <string>j099,woodford grn</string>\r\n  <string>l099,sw" +
            "19</string>\r\n  <string>l99,sw2</string>\r\n  <string>lam99,se1</string>\r\n  <string" +
            ">n99,n7</string>\r\n  <string>operation f99,w12</string>\r\n  <string>operation foxt" +
            "rot 99,w12</string>\r\n  <string>p099,se6</string>\r\n  <string>q99,wembley</string>" +
            "\r\n  <string>r99,se28</string>\r\n  <string>s099,n12</string>\r\n  <string>sv99,nw9</" +
            "string>\r\n  <string>td99,feltham</string>\r\n  <string>tj99,e1</string>\r\n  <string>" +
            "trojan 99,ec1</string>\r\n  <string>tx99,feltham</string>\r\n  <string>v099,sw19</st" +
            "ring>\r\n  <string>vw99,sw19</string>\r\n  <string>w99,sw18</string>\r\n  <string>x099" +
            ",w drayton</string>\r\n  <string>z099,kenley</string>\r\n  <string>j98,loughton</str" +
            "ing>\r\n  <string>n98,n7</string>\r\n  <string>t98,feltham</string>\r\n  <string>r97,s" +
            "e7</string>\r\n  <string>t97,richmond</string>\r\n  <string>tj97,se11</string>\r\n  <s" +
            "tring>bldg,building</string>\r\n  <string>bldg,buildings</string>\r\n</ArrayOfString" +
            ">")]
        public global::System.Collections.Specialized.StringCollection OldSyns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OldSyns"]));
            }
            set {
                this["OldSyns"] = value;
            }
        }
    }
}
