//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;

    public partial class Call
    {
        public int CallId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string Address6 { get; set; }
        public Nullable<int> Easting { get; set; }
        public Nullable<int> Northing { get; set; }
        public Nullable<int> SemiMajor { get; set; }
        public Nullable<int> SemiMinor { get; set; }
        public string Name { get; set; }
        public Nullable<int> Confidence { get; set; }
        public Nullable<int> Angle { get; set; }
        public Nullable<int> Altitude { get; set; }
        public Nullable<int> Direction { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> SwitchId { get; set; }
        public string Status { get; set; }
        public Nullable<int> Requery { get; set; }
        public string Extension { get; set; }
        public string Event { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> TimeConnected { get; set; }
        public Nullable<System.DateTime> TimeAnswered { get; set; }
        public Nullable<System.DateTime> TimeClosed { get; set; }
    }
}
