//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationView
    {
        public int DestinationID { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Status { get; set; }
        public Nullable<int> CoverageTier { get; set; }
        public Nullable<bool> IsOld { get; set; }
        public Nullable<bool> IsAandE { get; set; }
        public Nullable<bool> IsPolice { get; set; }
        public Nullable<bool> IsRoad { get; set; }
        public Nullable<bool> IsStation { get; set; }
        public Nullable<bool> IsStandby { get; set; }
        public Nullable<bool> IsHospital { get; set; }
        public string Shortcode { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    }
}
