//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRole
    {
        public DeviceRole()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int DeviceRoleID { get; set; }
        public string DeviceRoleName { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
    }
}
