//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;

    public partial class MapOverlayItemView
    {
        public int MapOverlayItemID { get; set; }
        public Nullable<float> FlashLimit { get; set; }
        public Nullable<float> RedLimit { get; set; }
        public Nullable<float> AmberLimit { get; set; }
        public byte[] CoverageMap { get; set; }
        public bool Visible { get; set; }
        public bool IsClosed { get; set; }
        public bool Flash { get; set; }
        public string FillColour { get; set; }
        public string Description { get; set; }
        public int MapOverlayID { get; set; }
        public string WKT { get; set; }
    }
}
