//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapOverlay
    {
        public MapOverlay()
        {
            this.MapOverlayItems = new HashSet<MapOverlayItem>();
        }
    
        public int MapOverlayID { get; set; }
        public string OverlayName { get; set; }
        public string Stroke { get; set; }
        public int StrokeThickness { get; set; }
        public int FromZoom { get; set; }
        public int ToZoom { get; set; }
        public int GeomUpdateFrequency { get; set; }
        public int AttrUpdateFrequency { get; set; }
        public Nullable<int> CalculateCoverage { get; set; }
    
        public virtual ICollection<MapOverlayItem> MapOverlayItems { get; set; }
    }
}
