//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OsmEntities : DbContext
    {
        public OsmEntities()
            : base("name=OsmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tMemberRole> tMemberRoles { get; set; }
        public virtual DbSet<tMemberType> tMemberTypes { get; set; }
        public virtual DbSet<tNode> tNodes { get; set; }
        public virtual DbSet<tRelation> tRelations { get; set; }
        public virtual DbSet<tRelationCreation> tRelationCreations { get; set; }
        public virtual DbSet<tWay> tWays { get; set; }
        public virtual DbSet<tWayCreation> tWayCreations { get; set; }
        public virtual DbSet<tNodeTag> tNodeTags { get; set; }
        public virtual DbSet<tRelationTag> tRelationTags { get; set; }
        public virtual DbSet<tTagType> tTagTypes { get; set; }
        public virtual DbSet<tWayTag> tWayTags { get; set; }
    }
}
