//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileParameterType
    {
        public ProfileParameterType()
        {
            this.ProfileParameters = new HashSet<ProfileParameter>();
        }
    
        public int ProfileParameterTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ProfileParameter> ProfileParameters { get; set; }
    }
}
