//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;

    public partial class ResourceStatusHistory
    {
        public int ResourceStatusHistoryID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<int> ResourceStatusID { get; set; }
        public Nullable<long> Revision { get; set; }
    
        public virtual ResourceStatu ResourceStatu { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
