//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;

    public partial class RoadLinkEdge
    {
        public int RoadLinkEdgeId { get; set; }
        public int RoadLinkId { get; set; }
        public string RoadName { get; set; }
        public int RoadTypeId { get; set; }
        public int SourceGrade { get; set; }
        public int TargetGrade { get; set; }
        public int Length { get; set; }
        public string WKT { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
    }
}
