//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{

    public partial class RoadLinkEdgeLink
    {
        public int RoadLinkEdgeLinkId { get; set; }
        public int SourceRoadLinkEdge { get; set; }
        public int TargetRoadLinkEdge { get; set; }
    }
}
