//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadSpeed
    {
        public int RoadSpeedId { get; set; }
        public double SpeedAvg { get; set; }
        public Nullable<double> SpeedStDev { get; set; }
        public int SpeedCount { get; set; }
        public int HourOfWeek { get; set; }
        public int VehicleId { get; set; }
        public Nullable<int> RoadLinkEdgeId { get; set; }
    }
}
