//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadSpeedMatrixDoW
    {
        public int RoadSpeedMatrixDoWId { get; set; }
        public int DayOfWeek { get; set; }
        public float AvgSpeed { get; set; }
        public int VehicleId { get; set; }
        public int GridX { get; set; }
        public int GridY { get; set; }
        public int RoadTypeId { get; set; }
    }
}
