//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuredItem
    {
        public SecuredItem()
        {
            this.SecuredItemLinks = new HashSet<SecuredItemLink>();
            this.SecuredItemLinks1 = new HashSet<SecuredItemLink>();
        }
    
        public int SecuredItemID { get; set; }
        public string SecuredItemName { get; set; }
        public string SecuredValue { get; set; }
        public string Description { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual ICollection<SecuredItemLink> SecuredItemLinks { get; set; }
        public virtual ICollection<SecuredItemLink> SecuredItemLinks1 { get; set; }
    }
}
