//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;

    public partial class SecuredItemLink
    {
        public int SecuredItemLinkId { get; set; }
        public Nullable<int> SecuredItemIDParent { get; set; }
        public Nullable<int> SecuredItemIDChild { get; set; }
    
        public virtual SecuredItem SecuredItem { get; set; }
        public virtual SecuredItem SecuredItem1 { get; set; }
    }
}
