//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRelation
    {
        public long id { get; set; }
        public System.Data.Entity.Spatial.DbGeography geo { get; set; }
        public int role { get; set; }
    }
}
