//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{

    public partial class tWayCreation
    {
        public long wayId { get; set; }
        public long nodeId { get; set; }
        public int sort { get; set; }
    }
}
