//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public int VariableID { get; set; }
        public string Variable1 { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
    }
}
