//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;

    public partial class AMPDScode
    {
        public short ampdsKey { get; set; }
        public string ampdscode1 { get; set; }
        public string chiefcomplaint { get; set; }
        public Nullable<byte> chiefcomplaintcode { get; set; }
        public string description { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public Nullable<byte> version { get; set; }
        public string category { get; set; }
        public string DefaultLASCategory { get; set; }
        public string DefaultLASCategoryFull { get; set; }
        public string DefaultDohCategory { get; set; }
        public string DefaultDohSubcategory { get; set; }
        public string DefaultDohSubcategoryFull { get; set; }
    }
}
