//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avl
    {
        public int RawAvlsId { get; set; }
        public Nullable<System.DateTime> AvlsDateTime { get; set; }
        public string Status { get; set; }
        public Nullable<short> Speed { get; set; }
        public Nullable<short> Direction { get; set; }
        public Nullable<decimal> LocationX { get; set; }
        public Nullable<decimal> LocationY { get; set; }
        public Nullable<short> FleetNumber { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public string Callsign { get; set; }
        public bool Scanned { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public string Category { get; set; }
        public Nullable<long> IncidentId { get; set; }
        public bool Process { get; set; }
        public Nullable<float> EstimatedSpeed { get; set; }
    }
}
