//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{

    public partial class CadLinkIncident
    {
        public int CadLinkId { get; set; }
        public string XmlData { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
