//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coverage
    {
        public int CoverageId { get; set; }
        public int VehicleTypeId { get; set; }
        public int DestinationId { get; set; }
        public byte[] CoverageMap { get; set; }
        public string Name { get; set; }
        public long OffsetX { get; set; }
        public long OffsetY { get; set; }
        public long BlockSize { get; set; }
        public long Rows { get; set; }
        public long Columns { get; set; }
    }
}
