//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationsView
    {
        public int DestinationId { get; set; }
        public string Destination { get; set; }
        public bool IsHospital { get; set; }
        public bool IsStandby { get; set; }
        public bool IsStation { get; set; }
        public bool IsRoad { get; set; }
        public double e { get; set; }
        public double n { get; set; }
        public Nullable<bool> IsPolice { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
