//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Determinant
    {
        public int DeterminantId { get; set; }
        public string determinant1 { get; set; }
        public string ambulances { get; set; }
        public string paramedics { get; set; }
        public string all_responders { get; set; }
        public string ecps { get; set; }
        public string comresp { get; set; }
    }
}
