//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighLevelList
    {
        public System.DateTime CallStart { get; set; }
        public Nullable<int> FRDelay { get; set; }
        public Nullable<int> AmbDelay { get; set; }
        public Nullable<int> TurnAround { get; set; }
        public Nullable<int> OnScene { get; set; }
        public string category { get; set; }
        public string ampdscode { get; set; }
        public Nullable<byte> version { get; set; }
    }
}
