//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public long cadref { get; set; }
        public string dohcategory { get; set; }
        public string dohsubcat { get; set; }
        public string lascat { get; set; }
        public Nullable<System.DateTime> callstart { get; set; }
        public Nullable<int> T0 { get; set; }
        public Nullable<int> T1 { get; set; }
        public Nullable<int> T2 { get; set; }
        public Nullable<int> T3 { get; set; }
        public string area { get; set; }
        public string postcode { get; set; }
        public string complaint { get; set; }
        public string AMPDS { get; set; }
        public Nullable<System.DateTime> firstdispatch { get; set; }
        public Nullable<System.DateTime> firstarrival { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> athospital { get; set; }
        public string hospital { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
    }
}
