//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulationIncident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimulationIncident()
        {
            this.SimulationResults = new HashSet<SimulationResult>();
        }
    
        public long IncidentId { get; set; }
        public System.DateTime CallStart { get; set; }
        public System.DateTime AMPDSTime { get; set; }
        public Nullable<int> Easting { get; set; }
        public Nullable<int> Northing { get; set; }
        public string AMPDSCode { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<bool> WasConveyed { get; set; }
        public Nullable<bool> WasDispatched { get; set; }
        public Nullable<bool> OutsideLAS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationResult> SimulationResults { get; set; }
    }
}
