//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulationAssignment
    {
        public int SimulationAssignments { get; set; }
        public Nullable<int> SimulationRunId { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public string Callsign { get; set; }
        public string Incident { get; set; }
        public string Action { get; set; }
    
        public virtual SimulationRun SimulationRun { get; set; }
    }
}
