//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;

    public partial class SimulationStat
    {
        public int SimulationStatsId { get; set; }
        public Nullable<int> SimulationRunId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Status { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
    
        public virtual SimulationRun SimulationRun { get; set; }
    }
}
