//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulationOrcon
    {
        public int SimulationOrconId { get; set; }
        public Nullable<int> SimulationRunId { get; set; }
        public Nullable<int> HourOrdinal { get; set; }
        public Nullable<int> catAOutside { get; set; }
        public Nullable<int> CatAInside { get; set; }
        public Nullable<int> CatBOutside { get; set; }
        public Nullable<int> CatBInside { get; set; }
        public Nullable<float> Performance { get; set; }
        public Nullable<float> PerfA { get; set; }
        public Nullable<float> PerfB { get; set; }
    
        public virtual SimulationRun SimulationRun { get; set; }
    }
}
