//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulationRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimulationRun()
        {
            this.SimulationAssignments = new HashSet<SimulationAssignment>();
            this.SimulationOrcons = new HashSet<SimulationOrcon>();
            this.SimulationResults = new HashSet<SimulationResult>();
            this.SimulationStats = new HashSet<SimulationStat>();
        }
    
        public int SimulationRunId { get; set; }
        public string Notes { get; set; }
        public string Constants { get; set; }
        public Nullable<float> Performance { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Stopped { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationAssignment> SimulationAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationOrcon> SimulationOrcons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationResult> SimulationResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationStat> SimulationStats { get; set; }
    }
}
