//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.SimulationResults = new HashSet<SimulationResult>();
            this.SimulationResults1 = new HashSet<SimulationResult>();
        }
    
        public int VehicleId { get; set; }
        public int VehicleTypeId { get; set; }
        public Nullable<int> SkillLevel { get; set; }
        public string MPCName { get; set; }
        public Nullable<int> Easting { get; set; }
        public Nullable<int> Northing { get; set; }
        public string Callsign { get; set; }
        public Nullable<int> FleetId { get; set; }
        public Nullable<int> DefaultDestinationId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationResult> SimulationResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationResult> SimulationResults1 { get; set; }
    }
}
