//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;

    public partial class VehicleRosterView
    {
        public string Name { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
    }
}
