//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;

    public partial class VehicleView
    {
        public int VehicleId { get; set; }
        public Nullable<int> SkillLevel { get; set; }
        public string VehicleType { get; set; }
        public int VehicleTypeId { get; set; }
        public string MPCName { get; set; }
        public Nullable<int> Northing { get; set; }
        public Nullable<int> Easting { get; set; }
        public string Callsign { get; set; }
        public Nullable<int> FleetId { get; set; }
        public Nullable<int> DefaultDestinationId { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
