//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Lib.Simulation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRoster
    {
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<int> minutesactual { get; set; }
        public string callsign { get; set; }
        public Nullable<int> easting { get; set; }
        public Nullable<int> northing { get; set; }
        public string stationID { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
    }
}
