version: '3'

services:
  quest.core:
    image: quest.core
    build:
      context: ./Quest.Core
      dockerfile: Dockerfile
    command: ["-exec=SearchManager","-components=components.json"]
       